name: 'PagerDuty Notifier'
author: 'Luis Masaya'
description: 'Send alert notification to PagerDuty on Pull Request'
branding:
  icon: 'alert-circle'
  color: 'green'
runs:
  using: 'docker'
  image: 'docker://lmasaya/pagerduty-notifier:0.1.1'
